readme.md

Use ES6 arrow function
Update from `+` to `*` to validate results

Use arrow function

---

readme.md

Can expand on this more. Not sure how much detail should be included.

Basic monad description

---

readme.md

I've tried to describe monoid in a way that doesn't use too much jargon :)

Add monoid description

---

readme.md

[Wikipedia][1]:
> In mathematics and computer science, a higher-order function […] is a function that does at least one of the following:
>
>   - takes one or more functions as arguments,
>   - returns a function as its result.
[1]: https://en.wikipedia.org/wiki/Higher-order_function

correct the definition of higher-order functions, and update examples

---

readme.md

I expanded the definitions of Arity, Lazy evaluation, and Monad. I may be able to do more, as I think this is a worthwhile project, but I want to make sure I’m not being too verbose. I’m still learning these concepts myself and find that trying to explain them is a good way of doing so!

Edit and expand Arity, Lazy Evaluation, and Monad definitions

---

readme.md

Ap, chain, lift. Minor change to monad(still needs work)

Added a couple descriptions

---

readme.md

Added isomorphic, Container type, removed duplicate chain. Simplified point-free example.

Additions and edits

---

readme.md

Minor tweaks to monoid def

---

readme.md

according to the way it's used, add should by curried

Point-Free Style: fix js error

---

readme.md

either this repository or this repo

small typo

---

readme.md

First off, this was very interesting to read and learn from, **huge thanks to all contributors**!!
There are quite a lot of changes, so please let me know which ones don't make sense to you and I'll revert them.
I've tried to make all the explanations and their respective code examples as "pretty" and consistent as possible.
Here's a list of what this PR contains:
- Typo, missing word and duplicate word corrections.
- Method names at the beginning of a sentence aren't capitalised (e.g. "`ap` applies a function in the object...")
- Give code snippets some space (1 empty line before and 1 after).
- All code snippets are now syntax highlighted with JS.
- Whitespaces in code snippets corrected.
Some suggestions / questions:
- Maybe have a TOC? (table of contents)
- Semicolons (everywhere vs. …

In-depth proofreading and correcting

---

contributing.md

This is obviously open to discussion but I thought it could help some people get started with contributing.

Styleguide2

---

readme.md

I think the diff shows the fix :-)

Fix spelling of "two two"

---

.gitignore
readme.md

Removed superflous <hr/>s
Added gitignore for build directory

Removed blockquotes #11

---

readme.md

The Functor section contained some redundant and overlapping descriptions. I restructured the paragraphs a bit to make it more clear.

Refine the Functor section

---

readme.md

The first change is not exactly necessary, but it would likely be wise to adhere to a standard. The second change, of course, fixes unnatural equality expectations ;)

Standardize and fix equality strictness in Setoid

---

readme.md

Partially addresses #70 and #72

Updated Applicative and Lift to partially address recent feedback

---

readme.md

This introduction introduces why this glossary is important and that the
examples are in JavaScript syntax.

Write a more complete introduction.

---

readme.md

I think it'd be best to shunt the meta stuff off to a separate document. I've created a wiki page for this purpose.

Moved the JavaScript justification over to a wiki.

---

readme.md

I really wasn't sure what you wanted for lodash, but it seems most sensible to me to just link the main lodash repo rather than the lodash/fp plugin specifically.

Did some light copy editing of the introductory text and added a list of FP libraries

---

readme.md

a). Initialization is a essential operation in `const` declaration, so `const greeting;` return compile error here
b). `let` is more accurate to express `mutable state`

Update the code snippet of purity

---

readme.md

Also added some example implementations of .ap and .chain
Regenerated TOC

Moved Libraries to the bottom, added auto curry, endomorphism

---

readme.md

#103: update Applicative Functor example

---

readme.md

Update for consistency with commit c9590ea (see #103 and #104).

Update Applicative Functor example

---

readme.md

Caught a small spelling error and wanted to fix.
Regards,

Fixes a tiny spelling error under auto currying.

---

.eslintrc.yml
contributing.md
package.json
readme.md

Added npm test for using code standards in the examples. #111

---

readme.md

Monad description mentions 'of' function; update the example to use this.

Update monad example

---

readme.md

Reading through this, the example code for the Purity information was a bit confusing.  The original example tried to show both using and changing global state in one function, but because of that the "pure" example and "unpure" example didn't actually do the same thing.
I think it's a little more clear if the two concepts are broken up, instead showing the "pure" version, one that uses global state, and one that modifies global state.

Update purity example

---

readme.md

add `Object.freeze()` to object defenition in Constant section

 fix: const can't guarantee object immutability

---

readme.md

I have translated the document completely into Spanish, I hope you can add me to the list of translations.
Greetings and happy new year :)

Added the translation into Spanish

---

readme.md

Added continuations with a short definition and example, and also added a brief commentary and example on how continuations are relevant in JavaScript async programming.
Closes #128

Continuations

---

readme.md

mori - open source taken from Clojure script
Immutable - by facebook

two new js libraries added

---

readme.md

Fixes https://github.com/hemanth/functional-programming-jargon/issues/137

Corrected definition of Category

---

readme.md

Use declarative programing instead of imperative programing.
Regards

Make easier for example of hoc

---

readme.md

it should be a middle dot from what I understand..

fix typo: middle dot

---

readme.md

Add translation for chinese

---

readme.md

Fix Typo in Closure

---

readme.md

redundant semicolon

---

readme.md

I like this functional programming article!
So I made a scala version translation for functional programming jargon.
Could you accept this PR? 😀
My work can see [this repo](https://github.com/ikhoon/functional-programming-jargon.scala/tree/master).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hemanth/functional-programming-jargon/175)

Add scala translation :-)

---

readme.md

I am interested in functional programming paradigm.
So I made Korean translation for functional programming jargon.
Thanks for the good info. 😄

Add Korean translation

---

readme.md

crocks is a collection of popular Algebraic Data Types (ADTs) that are all the rage in functional programming. The main goal of crocks is to curate and provide not only a common interface between each type (where possible of course), but also provide all of the helper functions needed to hit the ground running.

Added reference to Crocks ADT library

---

readme.md

Some examples of total/partial functions with general advices how to avoid partial functions

Added info about function totality

---

readme.md

This WIP statement was added 2 years ago. It seems like this project has reached a point of maturity I think it makes sense to remove this.

Remove WIP statement from README

---

readme.md

Adding fp-ts to the list of Functional Programming Libraries in JavaScript.

Adding fp-ts to the list of FP Libraries

---

readme.md

Eliminate usage of ≍

---

readme.md

- fix small typos,
- fix broken links,
- improve readability,
- harmonize formatting.

Polish readme.md

---

readme.md

If `f = x => x + 1` and `g = x => x * 2`,
then `some(1).map(x => g(f(x))) = g(1 + 1) = (1 + 1) * 2 = 4`.
See also #238.

Fix functor example

---

readme.md

fix: fix error in case of `Composable`
